"""Tom response generation foundation.

Converts a structured Command and optional ActionResult into a human-readable
TomResponse object.

Responsibilities:
- Generates natural, concise text responses for known intents.
- Formats local system time for the 'time' intent using the standard library.
- Formats success/failure status for 'open_app' based on ActionResult.
- Provides fallback / placeholder responses for unimplemented intents.

Does NOT:
- Access the microphone or audio system.
- Transcribe audio or parse intent.
- Execute actions or invoke subprocesses.
- Call external APIs, weather services, or LLMs.
- Perform text-to-speech.

Classes:
    TomResponse       — frozen dataclass holding response text and metadata
    ResponseGenerator — deterministic response generator
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from tom.actions import ActionResult
from tom.commands import Command
from tom.weather import WeatherRequest, WeatherResult, WEATHER_UNAVAILABLE, LOCATION_NOT_FOUND


# ---------------------------------------------------------------------------
# Response model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TomResponse:
    """Immutable structured response generated by Tom.

    Attributes:
        success: True if the command/action was handled successfully.
        text:    Human-readable response string to be displayed or spoken.
        intent:  The original command intent.
        target:  Optional target associated with the command or action.
    """

    success: bool
    text: str
    intent: str
    target: Optional[str] = None

    def __repr__(self) -> str:
        target_part = f", target={self.target!r}" if self.target is not None else ""
        return (
            f"TomResponse(success={self.success}, intent={self.intent!r}, "
            f"text={self.text!r}{target_part})"
        )


# ---------------------------------------------------------------------------
# ResponseGenerator
# ---------------------------------------------------------------------------

class ResponseGenerator:
    """Generates structured TomResponse objects from Commands and ActionResults.

    Pure deterministic formatting layer. No side effects, no subprocess,
    no external network calls.
    """

    def generate(
        self,
        command: Command,
        action_result: Optional[ActionResult] = None,
        *,
        weather_result: Optional[WeatherResult] = None,
    ) -> TomResponse:
        """Generate a TomResponse for the given command and optional action result.

        Args:
            command: The interpreted Command.
            action_result: Optional ActionResult if an action was executed.

        Returns:
            A TomResponse with appropriate text and success status.
        """
        if command.intent == "greeting":
            return self._handle_greeting(command)

        if command.intent == "time":
            return self._handle_time(command)

        if command.intent == "open_app":
            return self._handle_open_app(command, action_result)

        if command.intent == "weather":
            return self._handle_weather(command, weather_result)

        if command.intent == "exit":
            return self._handle_exit(command)

        return self._handle_unknown(command)

    # ------------------------------------------------------------------
    # Intent handlers
    # ------------------------------------------------------------------

    def _handle_greeting(self, command: Command) -> TomResponse:
        return TomResponse(
            success=True,
            text="Hello.",
            intent="greeting",
            target=None,
        )

    def _handle_time(self, command: Command) -> TomResponse:
        """Format the current local system time."""
        now = datetime.now().astimezone()
        time_str = now.strftime("%I:%M %p")
        if time_str.startswith("0"):
            time_str = time_str[1:]

        return TomResponse(
            success=True,
            text=f"The current time is {time_str}.",
            intent="time",
            target=None,
        )

    def _handle_open_app(
        self,
        command: Command,
        action_result: Optional[ActionResult],
    ) -> TomResponse:
        """Format response for open_app based on ActionResult."""
        if action_result is not None and action_result.success:
            app_name = action_result.target or command.target or "Application"
            return TomResponse(
                success=True,
                text=f"{app_name} is open.",
                intent="open_app",
                target=app_name,
            )

        # Failed or missing action result
        app_name = (
            (action_result.target if action_result else None)
            or command.target
            or "the application"
        )
        return TomResponse(
            success=False,
            text=f"I couldn't open {app_name}.",
            intent="open_app",
            target=app_name if app_name != "the application" else None,
        )

    def _handle_weather(self, command: Command, result: Optional[WeatherResult]) -> TomResponse:
        if result is None or not result.success:
            message = LOCATION_NOT_FOUND if result and result.message == LOCATION_NOT_FOUND else WEATHER_UNAVAILABLE
            return TomResponse(False, message, "weather")
        request = command.weather_request or WeatherRequest()
        location = result.location
        number = lambda value: f"{value:.0f}"
        if request.query_type == "rain":
            if result.precipitation_probability is None:
                return TomResponse(False, WEATHER_UNAVAILABLE, "weather")
            chance = result.precipitation_probability
            if chance <= 10:
                text = f"Rain is unlikely in {location} {request.period}, with about a {chance} percent chance."
            else:
                text = f"There's a {chance} percent chance of rain in {location} {request.period}."
        elif request.period == "tomorrow":
            if result.high_f is None or result.low_f is None:
                return TomResponse(False, WEATHER_UNAVAILABLE, "weather")
            text = f"Tomorrow in {location}, the high will be {number(result.high_f)} and the low {number(result.low_f)}"
            text += f", with {result.condition} conditions." if result.condition and request.query_type == "summary" else "."
        else:
            if result.temperature_f is None:
                return TomResponse(False, WEATHER_UNAVAILABLE, "weather")
            if request.query_type == "temperature":
                text = f"It's {number(result.temperature_f)} degrees in {location}"
                if result.apparent_temperature_f is not None:
                    text += f", and it feels like {number(result.apparent_temperature_f)}"
                text += "."
            else:
                if result.high_f is None or result.low_f is None:
                    return TomResponse(False, WEATHER_UNAVAILABLE, "weather")
                conditions = f" and {result.condition}" if result.condition else ""
                text = f"It's {number(result.temperature_f)} degrees{conditions} in {location}. "
                text += f"Today's high is {number(result.high_f)} and the low is {number(result.low_f)}."
        return TomResponse(True, text, "weather", target=location)

    def _handle_exit(self, command: Command) -> TomResponse:
        return TomResponse(
            success=True,
            text="Goodbye.",
            intent="exit",
            target=None,
        )

    def _handle_unknown(self, command: Command) -> TomResponse:
        return TomResponse(
            success=False,
            text="I don't know how to handle that yet.",
            intent=command.intent,
            target=command.target,
        )
