const { chromium } = require(process.env.TOM_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('fs');
(async () => {
 const base=process.env.TOM_TEST_URL || 'http://localhost:3017';
 const snap=await (await fetch(base+'/projects/drop/topology')).json();
 assert.equal(snap.project.name,'Drop'); assert.equal(snap.nodes.length,6); assert.equal(snap.edges.length,0);
 for (const id of ['invalid', '__proto__', 'constructor']) assert.equal((await fetch(base+'/projects/'+id+'/topology')).status,404);
 const before=fs.readFileSync(require('node:path').join(__dirname,'../.plugin-state/plugins.json'),'utf8');
 const browser=await chromium.launch({headless:true, channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:900}}); const errors=[], writes=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
 const nav=async name=>{await page.locator(`[data-page="${name}"]`).evaluate(e=>e.click());};
 await page.goto(base); await nav('topology'); await page.waitForSelector('.topo-node');
 assert.equal(await page.locator('.topo-node').count(),6); assert.equal(await page.locator('#topoEdges path').count(),0);
 await page.screenshot({path:require('node:os').tmpdir()+'/topology-desktop.png',fullPage:true});
 const node=page.locator('[data-node-id="plugin:github"]'); const p=await node.boundingBox();
 const old=await node.getAttribute('style');
 await page.mouse.move(p.x+50,p.y+30); await page.mouse.down(); await page.mouse.move(p.x+100,p.y+60,{steps:8}); await page.mouse.up();
 assert.notEqual(await node.getAttribute('style'),old); assert.equal(await page.locator('#topoPanel').isVisible(),false);
 await node.click(); assert.equal(await page.locator('#topoPanel').isVisible(),true);
 assert.equal(await page.locator('#topoPanel button').allTextContents().then(a=>a.some(x=>['Configure','Disconnect','Open','Test Connection'].includes(x))),false);
 await page.locator('.topo-close').click();
 const prev=await page.locator('#topoWorld').getAttribute('style'); await page.locator('#topoZoomIn').click(); assert.notEqual(await page.locator('#topoWorld').getAttribute('style'),prev);
 const canvas=await page.locator('#topologyCanvas').boundingBox(); const panBefore=await page.locator('#topoWorld').getAttribute('style');
 await page.mouse.move(canvas.x+20,canvas.y+90); await page.mouse.down(); await page.mouse.move(canvas.x+50,canvas.y+115,{steps:5}); await page.mouse.up();
 assert.notEqual(await page.locator('#topoWorld').getAttribute('style'),panBefore);
 await page.locator('#topoFit').click(); await page.locator('#topoSave').click();
 const saved=await page.evaluate(()=>localStorage.getItem('tom:topology:layout:v1:drop'));
 await page.reload(); await nav('topology'); await page.waitForSelector('.topo-node');
 assert.equal(await page.evaluate(()=>localStorage.getItem('tom:topology:layout:v1:drop')),saved);
 const layout=JSON.parse(saved); assert.ok(Math.abs(await node.evaluate(e=>parseFloat(e.style.left))-layout.positions['plugin:github'].x)<.01);
 await page.locator('#topoAuto').click(); await page.locator('#topoSearch').fill('GitHub'); assert.equal(await page.locator('.topo-node:visible').count(),2);
 await page.locator('#topoSearch').fill(''); await page.locator('[data-filter="connected"]').click(); assert.equal(await page.locator('.topo-node:visible').count(),1); await page.locator('[data-filter="all"]').click();
 await nav('marketplace'); await page.waitForSelector('.marketplace-card'); const catalog=await page.locator('.marketplace-card').count();
 await page.locator('#marketplaceSearch').fill('github'); await page.locator('.marketplace-card').first().click(); await page.locator('#detailBackButton').click(); assert.equal(await page.locator('#marketplaceSearch').inputValue(),'github');
 await nav('installed'); assert.equal(await page.locator('.installed-card').count(),5); await page.locator('.installed-card').first().click(); await page.locator('#detailBackButton').click(); assert.equal(await page.locator('#installed').evaluate(e=>e.classList.contains('active')),true);
 await nav('topology'); await node.click(); await page.locator('.topo-details').click(); await page.locator('#detailBackButton').click(); assert.equal(await page.locator('#topology').evaluate(e=>e.classList.contains('active')),true); await page.locator('.topo-close').click();
 const dimensions=[];
 for(const [width,height] of [[1440,900],[900,900],[390,844]]){
  await page.setViewportSize({width,height}); await page.locator('#topoFit').click();
  const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth})); assert.ok(sizes.scroll<=sizes.client,JSON.stringify({width,...sizes}));
  await page.screenshot({path:`/tmp/topology-${width}.png`,fullPage:true});
  await node.click(); assert.equal(await page.locator('#topoPanel').isVisible(),true); await page.screenshot({path:`/tmp/topology-panel-${width}.png`,fullPage:true}); await page.locator('.topo-close').click(); dimensions.push({width,height,...sizes});
 }
 await page.setViewportSize({width:1440,height:900}); await page.locator('#topoFit').click();
 await node.click(); await page.getByRole('tab',{name:'Permissions',exact:true}).click();
 await node.evaluate(e=>window.__originalTopologyNode=e);
 const retained=await page.locator('#topoWorld').getAttribute('style');
 await page.evaluate(()=>window.TomTopology.refresh());
 assert.equal(await node.evaluate(e=>e===window.__originalTopologyNode),true);
 assert.equal(await page.locator('#topoWorld').getAttribute('style'),retained);
 assert.equal(await page.getByRole('tab',{name:'Permissions',exact:true}).getAttribute('aria-selected'),'true');
 await page.route('**/projects/drop/topology',route=>route.fulfill({status:503,body:'unavailable'}));
 await page.evaluate(()=>window.TomTopology.refresh());
 assert.ok((await node.textContent()).includes('Stale / Unknown'));
 assert.equal(await page.locator('#topoHealth .state-unknown strong').textContent(),'5');
 await page.unroute('**/projects/drop/topology'); await page.evaluate(()=>window.TomTopology.refresh());
 assert.equal(await page.locator('#topoHealth .state-not_connected strong').textContent(),'5');
 assert.equal(await node.evaluate(e=>e===window.__originalTopologyNode),true);
 await page.locator('.topo-close').click();
 await page.emulateMedia({reducedMotion:'reduce'});
 const animation=await page.evaluate(()=>{const svg=document.querySelector('#topoEdges');const g=document.createElementNS(svg.namespaceURI,'g');g.setAttribute('class','state-working');const p=document.createElementNS(svg.namespaceURI,'path');g.append(p);svg.append(g);const value=getComputedStyle(p).animationName;g.remove();return value;});assert.equal(animation,'none');
 const cssErrors=await page.evaluate(()=>{const sheets=[...document.styleSheets].filter(s=>s.href?.endsWith('topology.css'));return sheets.map(s=>s.cssRules.length);}); assert.ok(cssErrors[0]>60);
 assert.equal(fs.readFileSync(require('node:path').join(__dirname,'../.plugin-state/plugins.json'),'utf8'),before);assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({api:'pass',nodes:snap.nodes.map(n=>n.label),edges:snap.edges.length,statuses:snap.nodes.slice(1).map(n=>[n.label,n.operationalStatus]),catalog,dimensions,drag:'pass',panZoom:'pass',saveReload:'pass',regressions:'pass',reducedMotion:'pass',writes,errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
